name: Forja Dual Monolítica Ultra Veloz Mesa 24

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del Repositorio Principal
        uses: actions/checkout@v4

      - name: Configurar Entorno de Herramientas Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y meson ninja-build cmake pkg-config python3-mako python3-pip zstd tar wget

      - name: Activar Android NDK Nativo del Servidor
        run: |
          NDK_SERVER_PATH=$(ls -d /usr/local/lib/android/sdk/ndk/* | tail -n 1)
          if [ -z "$NDK_SERVER_PATH" ]; then
            NDK_SERVER_PATH="/usr/local/lib/android/sdk/ndk-bundle"
          fi
          echo "-> Utilizando Android NDK lícito del servidor en la ruta: $NDK_SERVER_PATH"
          echo "ANDROID_NDK_LATEST_HOME=$NDK_SERVER_PATH" >> $GITHUB_ENV

      - name: Descargar Componentes de Shaders y Qualcomm Nativo
        run: |
          # BLINDAJE DE PORTAPAPELES: Declaramos las variables completas soldadas en una sola linea para que Git no sufra recortes del navegador
          URL_SPIRV="https://github.com"
          URL_HEADERS="https://github.com"
          URL_ADRENO="https://github.com"
          
          git clone --depth 1 "$URL_SPIRV" spirv_source
          git clone --depth 1 "$URL_HEADERS" spirv_source/external/spirv-headers
          git clone --depth 1 --recursive "$URL_ADRENO" adrenotools_source

      - name: Ejecutar Etapa A - Forja de Shaders (leegao)
        run: |
          sed -i 's/\r$//' compilar_shaders.sh || true
          chmod +x compilar_shaders.sh
          ./compilar_shaders.sh

      - name: Ejecutar Etapa B - Soldadura de Entorno y Stubs
        run: |
          sed -i 's/\r$//' preparar_entorno.sh || true
          chmod +x preparar_entorno.sh
          ./preparar_entorno.sh

      - name: Ejecutar Etapa C - Compilación Principal Mesa 24
        run: |
          sed -i 's/\r$//' build_mesa.sh || true
          chmod +x build_mesa.sh
          ./build_mesa.sh

      - name: Subir Fat Binary Dual Unificado a GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wrapper-vulkan-steven-mxz
          path: wrapper.tzst
          compression-level: 0
